apps:
  - name: stranger-things
    script: ./index.js
    max_memory_restart: 200M
    exec_mode: cluster
    instances: 2
    env_stranger-things:
      PORT: 3000
      REACT_APP_HAWKINS_URL: https://edibertooliveira-bk.herokuapp.com
      REACT_APP_HAWKINS_TIMEOUT: 30000
      REACT_APP_UPSIDEDOWN_URL: https://edibertooliveira-bd.herokuapp.com
      REACT_APP_UPSIDEDOWN_TIMEOUT: 30000
